# Generated by Django 2.2.6 on 2019-12-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Cargo',
        ),
    ]
