# Generated by Django 2.2.6 on 2019-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_auto_20191202_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name_plural': 'Cargo'},
        ),
        migrations.AddField(
            model_name='cargo',
            name='especificacoes_do_cargo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='forma_de_contratacao',
            field=models.CharField(blank=True, choices=[('CT', 'CLT'), ('T', 'TEMPORARIO'), ('C', 'CONTRATO POR EMPREITADA')], max_length=1),
        ),
        migrations.AddField(
            model_name='cargo',
            name='outros',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cargo',
            name='remuneracao',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='cargo',
            name='turno',
            field=models.CharField(choices=[('C', 'COMERCIAL'), ('M', 'MATUTINO'), ('V', 'VESPERTINO'), ('N', 'NOTURNO')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='cargo',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='cargo',
            name='vale_refeicao',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NAO')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='cargo',
            name='vale_transporte',
            field=models.CharField(choices=[('S', 'SIM'), ('N', 'NAO')], default=0, max_length=1),
        ),
    ]
