# Generated by Django 3.0 on 2019-12-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_auto_20191213_1821'),
        ('vagas', '0007_auto_20191213_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='candidato',
            field=models.ManyToManyField(to='candidato.Candidato'),
        ),
    ]
