# Generated by Django 3.0 on 2019-12-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0008_vagas_candidato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagas',
            name='candidato',
        ),
    ]
