# Generated by Django 3.0 on 2019-12-14 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0009_remove_vagas_candidato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vagas',
            old_name='nome',
            new_name='cargo',
        ),
    ]
