# Generated by Django 3.0 on 2019-12-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0009_remove_vagas_candidato'),
        ('candidato', '0003_auto_20191213_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='vagas',
            field=models.ManyToManyField(to='vagas.Vagas'),
        ),
    ]
