# Generated by Django 3.0 on 2019-12-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0005_auto_20191214_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='vagas',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(blank=True, max_length=60),
        ),
    ]
