# Generated by Django 3.0 on 2019-12-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0006_auto_20191214_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='vagas',
            field=models.ManyToManyField(related_name='_candidato_vagas_+', to='candidato.Candidato'),
        ),
    ]
