# Generated by Django 3.0 on 2019-12-15 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0008_auto_20191214_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='Endereco',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='Tipo_de_Endereco',
            new_name='tipo_de_endereco',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='logradouro',
        ),
    ]
