# Generated by Django 3.0 on 2019-12-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0009_auto_20191214_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='bairro',
            field=models.CharField(max_length=60, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cep',
            field=models.CharField(max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cidade',
            field=models.CharField(max_length=30, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='data_de_expedicao',
            field=models.DateField(max_length=8, verbose_name='Data de Expedição'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='data_de_nascimento',
            field=models.DateField(max_length=20, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(blank=True, max_length=60, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='endereco',
            field=models.CharField(max_length=60, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTEIRO', 'SOLTEIRO'), ('CASADO', 'CASADO(A)'), ('VIUVO', 'VIÚVO(A)'), ('UNIAO ESTAVEL', 'UNIAO ESTÁVEL')], default=0, max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome_completo',
            field=models.CharField(max_length=500, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='orgao_expedidor',
            field=models.CharField(max_length=30, verbose_name='Orgão Expedidor'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='rg',
            field=models.CharField(max_length=30, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='site',
            field=models.CharField(blank=True, max_length=60, verbose_name='Sítio'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tipo_de_endereco',
            field=models.CharField(blank=True, choices=[('RES', 'RESIDENCIAL'), ('COM', 'COMÉRCIAL'), ('URB', 'URBANO'), ('RUR', 'RURAL')], max_length=3, verbose_name='Tipo de Endereço'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=0, max_length=3, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='uf_da_expedicao',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=0, max_length=3, verbose_name='UF'),
        ),
    ]
