# Generated by Django 3.0 on 2019-12-15 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0010_auto_20191214_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia_Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150, verbose_name='Empresa')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('tarefas_executadas', models.TextField(verbose_name='Tarefas Executadas')),
                ('forma_de_contratacao', models.CharField(blank=True, choices=[('T', 'CLT'), ('T', 'TEMPORARIO'), ('C', 'CONTRATO POR EMPREITADA'), ('O', 'Outra')], max_length=1, verbose_name='Forma de Contratação')),
                ('data_de_inicio', models.DateField(max_length=12, verbose_name='Data de Início')),
                ('data_fim', models.DateField(max_length=12, verbose_name='Data da Saída do Emprego')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.Candidato')),
            ],
        ),
    ]
