# Generated by Django 3.0 on 2019-12-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0011_experiencia_profissional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencia_profissional',
            options={'verbose_name': 'Experiência Profissional', 'verbose_name_plural': 'Experiências Profissionais'},
        ),
    ]
