# Generated by Django 3.0 on 2019-12-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Razao_Social', models.CharField(max_length=500)),
                ('cnpj', models.CharField(max_length=14)),
                ('Tipo_de_Endereco', models.CharField(blank=True, choices=[('RES', 'RESIDENCIAL'), ('COM', 'COMÉRCIAL'), ('URB', 'URBANO'), ('RUR', 'RURAL')], max_length=3)),
                ('Endereco', models.CharField(max_length=60)),
                ('logradouro', models.CharField(max_length=60)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=8)),
                ('uf', models.CharField(max_length=30)),
                ('telefones', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=60)),
                ('site', models.CharField(max_length=60)),
                ('area_de_atuacao', models.CharField(blank=True, choices=[('IND', 'INDÚSTRIA'), ('COM', 'COMÉRCIO'), ('SER', 'SERVIÇOS'), ('ALI', 'ALIMENTAÇÃO'), ('SPO', 'ESPORTES'), ('TIC', 'TECNOLOGIA DA INFORMAÇÃO E COMUNICAÇÃO')], max_length=3)),
            ],
            options={
                'verbose_name_plural': 'Cadastrar',
            },
        ),
        migrations.DeleteModel(
            name='Cadastrar',
        ),
    ]
