# Generated by Django 3.0 on 2019-12-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20191212_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cep',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
    ]
