# Generated by Django 3.0 on 2019-12-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20191214_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='Endereco',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='Razao_Social',
            new_name='razao_social',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='Tipo_de_Endereco',
            new_name='tipo_de_endereco',
        ),
    ]
